name: Run Tests

on: [push, pull_request]

jobs:
  test-frontend:
    name: Test Frontend (React Native)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run Jest tests
        run: npm test

  test-backend:
    name: Test Backend (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use your project's python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Or however you manage dependencies
          pip install pytest
      - name: Run pytest
        run: pytest
